"use client";

import { useState, useEffect } from "react";
import {
    AlertTriangle,
    Zap,
    Users,
    CheckCircle2,
    Archive,
    Share2,
    MessageSquare,
    Check,
    ShieldAlert,
    FileText,
    Lightbulb,
    Bookmark
} from "lucide-react";
import { toast } from "sonner";
import ReactMarkdown from "react-markdown";
import { cn } from "@/lib/utils";
import { markAsReadAction, archiveItemAction, toggleBookmarkAction } from "@/app/(dashboard)/inbox/actions";
import { PremiumCard } from "@/components/ui/PremiumCard";
import { motion } from "framer-motion";
import { Button } from "@/components/ui/button";
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from "@/components/ui/tooltip";

interface InboxDetailViewProps {
    item: Record<string, unknown>;
    onUpdate: () => void;
}

function SourceIcon({ source, className }: { source: string; className?: string }) {
    if (source === "alert") return <AlertTriangle className={className} />;
    if (source === "summary") return <FileText className={className} />;
    return <Lightbulb className={className} />;
}

function sourceBg(source: string) {
    if (source === "alert") return "bg-red-500/10 border border-red-500/20 text-red-600 dark:text-red-400";
    if (source === "summary") return "bg-primary/10 border border-primary/20 text-primary";
    return "bg-green-500/10 border border-green-500/20 text-green-600 dark:text-green-400";
}

function sourceLabel(source: string) {
    if (source === "alert") return "Alert";
    if (source === "summary") return "Summary";
    return "Insight";
}

export function InboxDetailView({ item, onUpdate }: InboxDetailViewProps) {
    const [checklist, setChecklist] = useState<Record<string, boolean>>({});
    const [archiving, setArchiving] = useState(false);
    const [resolving, setResolving] = useState(false);
    const [bookmarked, setBookmarked] = useState(item.is_bookmarked || false);

    // Sync local state when the item changes
    useEffect(() => {
        setBookmarked(item.is_bookmarked || false);
    }, [item.id, item.is_bookmarked]);

    const toggleCheck = (index: number) => {
        setChecklist(prev => ({ ...prev, [index]: !prev[index] }));
    };

    const handleArchive = async () => {
        setArchiving(true);
        await archiveItemAction(item.id, item.source);
        toast.success("Mensagem arquivada com sucesso");
        onUpdate();
        setArchiving(false);
    };

    const handleResolve = async () => {
        setResolving(true);
        await markAsReadAction(item.id, item.source);
        toast.success("Mensagem marcada como resolvida/lida");
        onUpdate();
        setResolving(false);
    };

    const handleBookmark = async () => {
        const newState = !bookmarked;
        setBookmarked(newState);
        await toggleBookmarkAction(item.id, item.source, newState);
        if (newState) {
            toast.success("Mensagem favoritada");
        } else {
            toast.info("Mensagem removida dos favoritos");
        }
        onUpdate();
    };

    const handleShare = () => {
        const text = `*IgnoHub Intelligence Report*\n\n*Type:* ${sourceLabel(item.source)}\n*Title:* ${item.title}\n*Group:* ${item.group_name}\n\n${item.summary || item.summary_text || item.insight_text}\n\n_Generated by IgnoHub AI_`;
        navigator.clipboard.writeText(text);
        toast.success("Texto copiado para a área de transferência!");
    };

    const renderAlertView = () => (
        <div className="space-y-6">
            {/* Risk bar */}
            <div className="space-y-2">
                <p className="text-xs font-medium text-muted-foreground">Risk level</p>
                <div className="h-2 w-full bg-muted rounded-full overflow-hidden">
                    <motion.div
                        initial={{ width: 0 }}
                        animate={{
                            width: item.severity === "high" ? "90%" : item.severity === "medium" ? "50%" : "20%"
                        }}
                        transition={{ duration: 0.8, ease: "easeOut" }}
                        className={cn(
                            "h-full rounded-full",
                            item.severity === "high" ? "bg-destructive" :
                                item.severity === "medium" ? "bg-amber-500" : "bg-green-500"
                        )}
                    />
                </div>
                <div className="flex items-center justify-between text-xs text-muted-foreground">
                    <span className="capitalize">{item.severity || "low"}</span>
                    <span className="font-mono font-medium">
                        {item.score || (item.severity === "high" ? "9.2" : "4.5")} / 10
                    </span>
                </div>
            </div>

            {/* Evidence */}
            {(item.evidence_excerpt) && (
                <div className="space-y-2">
                    <div className="flex items-center gap-1.5 text-xs font-medium text-muted-foreground">
                        <ShieldAlert className="h-3.5 w-3.5" />
                        Evidence
                    </div>
                    <blockquote className="pl-4 border-l-2 border-primary text-sm text-muted-foreground italic leading-relaxed">
                        &quot;{item.evidence_excerpt}&quot;
                    </blockquote>
                </div>
            )}

            {/* Recommended Actions */}
            {(item.recommended_actions?.length > 0) && (
                <div className="space-y-2">
                    <p className="text-xs font-medium text-muted-foreground">Recommended actions</p>
                    <div className="grid gap-2">
                        {item.recommended_actions.map((action: string, idx: number) => (
                            <button
                                key={idx}
                                onClick={() => toggleCheck(idx)}
                                className={cn(
                                    "flex items-center gap-3 p-3 rounded-lg text-left text-sm transition-colors border",
                                    checklist[idx]
                                        ? "bg-green-50 dark:bg-green-900/20 border-green-200 dark:border-green-800 text-green-700 dark:text-green-400"
                                        : "bg-card border-border text-foreground hover:bg-accent/50"
                                )}
                            >
                                <div className={cn(
                                    "h-4 w-4 rounded border flex items-center justify-center shrink-0 transition-colors",
                                    checklist[idx]
                                        ? "bg-green-600 dark:bg-green-500 border-transparent text-white"
                                        : "border-input"
                                )}>
                                    {checklist[idx] && <Check className="h-2.5 w-2.5 stroke-[3]" />}
                                </div>
                                <span>{action}</span>
                            </button>
                        ))}
                    </div>
                </div>
            )}
        </div>
    );

    const renderSummaryView = () => (
        <div className="space-y-6">
            <div className="space-y-2">
                <p className="text-xs font-medium text-muted-foreground">AI Summary</p>
                <div className="prose prose-sm prose-slate dark:prose-invert max-w-none rounded-lg bg-card p-5 border border-border text-sm leading-relaxed">
                    <ReactMarkdown>{item.summary_text || item.summary}</ReactMarkdown>
                </div>
            </div>

            {item.highlights && Object.keys(item.highlights).length > 0 && (
                <div className="space-y-2">
                    <p className="text-xs font-medium text-muted-foreground">Highlights</p>
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                        {Object.entries((item.highlights as Record<string, unknown>) || {}).map(([key, value]) => (
                            <PremiumCard key={key} className="p-4">
                                <div className="flex items-start gap-3">
                                    <div className="w-7 h-7 bg-primary/10 rounded-md flex items-center justify-center text-primary shrink-0">
                                        <Zap className="h-3.5 w-3.5" />
                                    </div>
                                    <div>
                                        <p className="text-xs font-medium text-muted-foreground mb-0.5">{key}</p>
                                        <p className="text-sm font-semibold text-foreground">
                                            {typeof value === "object" ? JSON.stringify(value) : value}
                                        </p>
                                    </div>
                                </div>
                            </PremiumCard>
                        ))}
                    </div>
                </div>
            )}
        </div>
    );

    const renderInsightView = () => (
        <div className="space-y-6">
            <PremiumCard className="p-4">
                <div className="flex items-center gap-3">
                    <div className="w-10 h-10 bg-muted rounded-lg flex items-center justify-center">
                        <Users className="h-5 w-5 text-muted-foreground" />
                    </div>
                    <div>
                        <p className="text-xs text-muted-foreground">Source identifier</p>
                        <p className="text-sm font-mono font-medium text-foreground">
                            {item.author_hash?.slice(0, 16)}...
                        </p>
                        <div className="flex gap-2 mt-1.5">
                            <span className="text-[11px] px-2 py-0.5 rounded-full bg-primary text-primary-foreground font-medium">
                                Key account
                            </span>
                            <span className="text-[11px] px-2 py-0.5 rounded-full bg-muted text-muted-foreground font-medium">
                                {item.role || "Member"}
                            </span>
                        </div>
                    </div>
                </div>
            </PremiumCard>

            <div className="space-y-2">
                <p className="text-xs font-medium text-muted-foreground">Behavioral insight</p>
                <div className="rounded-lg border border-border bg-card p-5">
                    <div className="flex gap-3">
                        <MessageSquare className="h-4 w-4 text-muted-foreground mt-0.5 shrink-0" />
                        <p className="text-sm text-foreground leading-relaxed">
                            {item.insight_text || item.summary}
                        </p>
                    </div>
                </div>
            </div>
        </div>
    );

    return (
        <div className="flex flex-col h-full">
            {/* Header */}
            <div className="px-6 py-4 border-b border-border space-y-3 bg-card/80 sticky top-0 z-10 backdrop-blur-sm">
                <div className="flex items-center justify-between">
                    <div className="flex items-center gap-2.5">
                        <div className={cn("w-7 h-7 rounded-lg flex items-center justify-center", sourceBg(item.source))}>
                            <SourceIcon source={item.source} className="h-3.5 w-3.5" />
                        </div>
                        <div>
                            <span className="text-xs font-medium text-muted-foreground">
                                {sourceLabel(item.source)} · {item.group_name}
                            </span>
                        </div>
                    </div>
                    <span className="text-xs text-muted-foreground">
                        {new Date(item.created_at).toLocaleString([], { dateStyle: "medium", timeStyle: "short" })}
                    </span>
                </div>
                <h2 className="text-base font-semibold text-foreground leading-snug">
                    {item.title}
                </h2>
            </div>

            {/* Content */}
            <div className="flex-1 overflow-y-auto p-6">
                <motion.div
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    transition={{ duration: 0.2 }}
                >
                    {item.source === "alert" && renderAlertView()}
                    {item.source === "summary" && renderSummaryView()}
                    {item.source === "insight" && renderInsightView()}
                </motion.div>
            </div>

            {/* Footer Actions */}
            <div className="px-6 py-4 border-t border-border bg-card flex items-center justify-between gap-2">
                <TooltipProvider delayDuration={200}>
                    <div className="flex gap-2">
                        <Tooltip>
                            <TooltipTrigger asChild>
                                <Button
                                    variant="outline"
                                    size="sm"
                                    onClick={handleArchive}
                                    disabled={archiving}
                                    className="gap-1.5"
                                >
                                    <Archive className="h-3.5 w-3.5" />
                                    Arquivar
                                </Button>
                            </TooltipTrigger>
                            <TooltipContent>
                                <p>Ocultar mensagem da caixa de entrada principal.</p>
                            </TooltipContent>
                        </Tooltip>

                        <Tooltip>
                            <TooltipTrigger asChild>
                                <Button
                                    variant="outline"
                                    size="sm"
                                    onClick={handleResolve}
                                    disabled={resolving || item.is_resolved}
                                    className="gap-1.5"
                                >
                                    <CheckCircle2 className="h-3.5 w-3.5" />
                                    {item.is_resolved ? 'Resolvido' : 'Resolver'}
                                </Button>
                            </TooltipTrigger>
                            <TooltipContent>
                                <p>Marcar o item de inteligência ou risco como avaliado.</p>
                            </TooltipContent>
                        </Tooltip>
                    </div>
                </TooltipProvider>

                <TooltipProvider delayDuration={200}>
                    <div className="flex gap-2">
                        <Tooltip>
                            <TooltipTrigger asChild>
                                <Button
                                    variant={bookmarked ? "secondary" : "ghost"}
                                    size="icon"
                                    onClick={handleBookmark}
                                    className={cn("h-8 w-8", bookmarked && "text-brand-500 bg-brand-500/10")}
                                >
                                    <Bookmark className={cn("h-4 w-4", bookmarked && "fill-brand-500")} />
                                </Button>
                            </TooltipTrigger>
                            <TooltipContent>
                                <p>Favoritar mensagem para acesso rápido.</p>
                            </TooltipContent>
                        </Tooltip>

                        <Tooltip>
                            <TooltipTrigger asChild>
                                <Button
                                    size="sm"
                                    onClick={handleShare}
                                    className="gap-1.5"
                                >
                                    <Share2 className="h-3.5 w-3.5" />
                                    Compartilhar
                                </Button>
                            </TooltipTrigger>
                            <TooltipContent>
                                <p>Copiar um resumo para a área de transferência.</p>
                            </TooltipContent>
                        </Tooltip>
                    </div>
                </TooltipProvider>
            </div>
        </div>
    );
}
